### ISSUE TITLE
Some feedback after use

### ISSUE THREAD

**Issue by DFBR1208** [9tarek/8DX-Mogi-Table-Bot#2]
Hello, I was able to find the program anb been using for a while and here is some feedback and possible requests that would at least improve my experience, first of all I'd like to thk u for creating this, I've actually dreamed about having a way to make auto scores via sreams screenshots but I don't have the programming knowledge to put it to work

1. Twitch hotkey not working; yeah, I know it's extremely experimental ofc, just reporting it, been using the normal hotkey with full screen as recommended and it works like a charm for most of the times, still in this topic, it could have an option to clear hotkey, since I tried to test twitch screenshot I enabled one hotkey but was not able to remove after

2. Show full TAG on OBS overlay; the program can recognize full tags as seen in the table tab, but in the OBS overlay it only shows one character, I guess this is made on purpose, but it could have an option to enable full tags in the overlay or maybe a character limit in order to not mess-up the style, sorry, I'm just spilling things without knowledge of programming.

3. Show score difference and full tags in score copy/paste; simillar to last topic, the copy/paste score only shows one character tag, the score of witch one and races left, in the overlay there's the score difference so it would be nice to have at least an option to show score differences and full tags simillar to the one used in https://gungeespla.github.io/mk8dx_sokuji/ (witch I guess is the reference project you used)

4. Manually set tags; sometimes the program fails to indentify some tags due to simillarity, maybe being able to set tags (before or durring the mogi) could solve this

Anyway, again I'm reporting as a user without programming knowledge and with resources that would improve my own experience, thank you for the attention!!

**Comment by DFBR1208** [comment]
Some other things

4. Manually set tags; sometimes the program fails to indentify some tags due to simillarity, maybe being able to set tags (before or durring the mogi) could solve this

5. Submit table don't do nothing (I imagine); I imagine that this feature is robably planned for being able to submit the table automatic to the lounge discord, but for now it's not working.

**Comment by 9tarek** [comment]
Hi! 
Thanks for reaching out to me.
1. There actually is a way to unbind the twitch hotkey, if you bind it to ESC, but i guess i forgot to mention it lmao.
2. & 3. I can def implement that!
4. This wouldnt change anything, because if it reads it wrong it will still read it wrong if i'd set it beforehand. But out of curiosity, what are the tags youre having troubles with, and is the problem only on the table or on the overlay aswell.

and i dont understand the 5. point. where do you have an option to submit the table? The only submit button i can think of is for the dc points. The bot is not able to send anything to discord, let alone access it

(thanks for sending me the other project i actually did not know about it, my reference was sheat lol)

**Comment by DFBR1208** [comment]
Hi again, yep the 5 was totally wrong, that's why I removed it after edit

about 4, the one with most difficult was B been mistaked as 8, some others were completely random and broken, it happens

Thx for the answer!! looking further on the project!!

**Comment by 9tarek** [comment]
I see,
Tag 8 and B is actually fixed in the latest version (2.0.2) but yea sometimes it messes it up when the background is bad.
I'll implement your other points when i get to it.
Thanks for the feedback
